name: Unity Windows BuildAdd commentMore actions

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  build:
    name: Build for Windows 64-bit
    runs-on: ubuntu-latest # Unity can cross-compile to Windows from Linux
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true # Important for Git LFS files
